import Link from "next/link";

import { listCourses } from "@/services/admin/admin.service";

export default async function AdminCoursesPage({ searchParams }: { searchParams: Promise<{ search?: string }> }) {
  const { search = "" } = await searchParams;
  const result = await listCourses(search, 1, 50);
  return <main><div className="mb-8 flex items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-indigo-600">Administration</p><h1 className="mt-2 text-3xl font-semibold">Courses</h1><p className="mt-2 text-zinc-600">Course catalogue and lecturer assignments.</p></div><Link className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white hover:bg-indigo-700" href="/admin/courses/new">Create course</Link></div><form className="mb-4 flex gap-2" method="get"><input className="h-10 flex-1 rounded-lg border border-zinc-300 px-3" defaultValue={search} name="search" placeholder="Search course code or title"/><button className="rounded-lg border border-zinc-300 px-4 text-sm font-semibold" type="submit">Search</button></form><div className="overflow-x-auto rounded-xl border border-zinc-200 bg-white"><table className="min-w-full text-left text-sm"><thead className="border-b border-zinc-200 bg-zinc-50 text-zinc-600"><tr><th className="px-4 py-3">Code</th><th className="px-4 py-3">Title</th><th className="px-4 py-3">Department</th><th className="px-4 py-3">Lecturer</th><th className="px-4 py-3">Status</th></tr></thead><tbody>{result.items.map((course) => <tr className="border-b border-zinc-100 last:border-0" key={course.id}><td className="px-4 py-3 font-medium">{course.code}</td><td className="px-4 py-3">{course.title}</td><td className="px-4 py-3">{course.department.code}</td><td className="px-4 py-3">{course.lecturer.user.fullName}</td><td className="px-4 py-3">{course.isActive ? "ACTIVE" : "INACTIVE"}</td></tr>)}</tbody></table>{result.items.length === 0 ? <p className="p-8 text-center text-zinc-500">No courses found.</p> : null}</div></main>;
}
