import Link from "next/link";

import { listDepartments } from "@/services/admin/admin.service";

export default async function AdminDepartmentsPage({ searchParams }: { searchParams: Promise<{ search?: string }> }) {
  const { search = "" } = await searchParams;
  const departments = await listDepartments(search);
  return <main><div className="mb-8 flex items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-indigo-600">Administration</p><h1 className="mt-2 text-3xl font-semibold">Departments</h1><p className="mt-2 text-zinc-600">Academic departments and their current relationships.</p></div><Link className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white hover:bg-indigo-700" href="/admin/departments/new">Create department</Link></div><form className="mb-4 flex gap-2" method="get"><input className="h-10 flex-1 rounded-lg border border-zinc-300 px-3" defaultValue={search} name="search" placeholder="Search department name or code"/><button className="rounded-lg border border-zinc-300 px-4 text-sm font-semibold" type="submit">Search</button></form><div className="overflow-x-auto rounded-xl border border-zinc-200 bg-white"><table className="min-w-full text-left text-sm"><thead className="border-b border-zinc-200 bg-zinc-50 text-zinc-600"><tr><th className="px-4 py-3">Code</th><th className="px-4 py-3">Name</th><th className="px-4 py-3">Students</th><th className="px-4 py-3">Lecturers</th><th className="px-4 py-3">Courses</th></tr></thead><tbody>{departments.map((department) => <tr className="border-b border-zinc-100 last:border-0" key={department.id}><td className="px-4 py-3 font-medium">{department.code}</td><td className="px-4 py-3">{department.name}</td><td className="px-4 py-3">{department._count.students}</td><td className="px-4 py-3">{department._count.lecturers}</td><td className="px-4 py-3">{department._count.courses}</td></tr>)}</tbody></table>{departments.length === 0 ? <p className="p-8 text-center text-zinc-500">No departments found.</p> : null}</div></main>;
}
